language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r fair/tests/requirements.txt
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
- python setup.py install
script:
- python setup.py check -rms
- flake8
- pytest